//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageDataLibrary.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageItem", Namespace="http://schemas.datacontract.org/2004/07/ImageDataLibrary.Models")]
    public partial class ImageItem : ImageDataLibrary.Models.ImageCommon
    {
        
        private byte[] ThumbnailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Thumbnail
        {
            get
            {
                return this.ThumbnailField;
            }
            set
            {
                this.ThumbnailField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageCommon", Namespace="http://schemas.datacontract.org/2004/07/ImageDataLibrary.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ImageDataLibrary.Models.FullImage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ImageDataLibrary.Models.ImageItem))]
    public partial class ImageCommon : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid _idField;
        
        private byte[] _imageDataField;
        
        private string _imageNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid _id
        {
            get
            {
                return this._idField;
            }
            set
            {
                this._idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] _imageData
        {
            get
            {
                return this._imageDataField;
            }
            set
            {
                this._imageDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _imageName
        {
            get
            {
                return this._imageNameField;
            }
            set
            {
                this._imageNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullImage", Namespace="http://schemas.datacontract.org/2004/07/ImageDataLibrary.Models")]
    public partial class FullImage : ImageDataLibrary.Models.ImageCommon
    {
        
        private byte[] FullImageDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FullImageData
        {
            get
            {
                return this.FullImageDataField;
            }
            set
            {
                this.FullImageDataField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IImageService")]
public interface IImageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageList", ReplyAction="http://tempuri.org/IImageService/GetImageListResponse")]
    ImageDataLibrary.Models.ImageItem[] GetImageList();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageList", ReplyAction="http://tempuri.org/IImageService/GetImageListResponse")]
    System.Threading.Tasks.Task<ImageDataLibrary.Models.ImageItem[]> GetImageListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageById", ReplyAction="http://tempuri.org/IImageService/GetImageByIdResponse")]
    ImageDataLibrary.Models.FullImage GetImageById(System.Guid imageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/GetImageById", ReplyAction="http://tempuri.org/IImageService/GetImageByIdResponse")]
    System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> GetImageByIdAsync(System.Guid imageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/PostImage", ReplyAction="http://tempuri.org/IImageService/PostImageResponse")]
    ImageDataLibrary.Models.FullImage PostImage(ImageDataLibrary.Models.FullImage image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/PostImage", ReplyAction="http://tempuri.org/IImageService/PostImageResponse")]
    System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> PostImageAsync(ImageDataLibrary.Models.FullImage image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/PutImage", ReplyAction="http://tempuri.org/IImageService/PutImageResponse")]
    ImageDataLibrary.Models.FullImage PutImage(ImageDataLibrary.Models.FullImage image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/PutImage", ReplyAction="http://tempuri.org/IImageService/PutImageResponse")]
    System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> PutImageAsync(ImageDataLibrary.Models.FullImage image);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImage", ReplyAction="http://tempuri.org/IImageService/DeleteImageResponse")]
    bool DeleteImage(System.Guid id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageService/DeleteImage", ReplyAction="http://tempuri.org/IImageService/DeleteImageResponse")]
    System.Threading.Tasks.Task<bool> DeleteImageAsync(System.Guid id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IImageServiceChannel : IImageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImageServiceClient : System.ServiceModel.ClientBase<IImageService>, IImageService
{
    
    public ImageServiceClient()
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ImageDataLibrary.Models.ImageItem[] GetImageList()
    {
        return base.Channel.GetImageList();
    }
    
    public System.Threading.Tasks.Task<ImageDataLibrary.Models.ImageItem[]> GetImageListAsync()
    {
        return base.Channel.GetImageListAsync();
    }
    
    public ImageDataLibrary.Models.FullImage GetImageById(System.Guid imageId)
    {
        return base.Channel.GetImageById(imageId);
    }
    
    public System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> GetImageByIdAsync(System.Guid imageId)
    {
        return base.Channel.GetImageByIdAsync(imageId);
    }
    
    public ImageDataLibrary.Models.FullImage PostImage(ImageDataLibrary.Models.FullImage image)
    {
        return base.Channel.PostImage(image);
    }
    
    public System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> PostImageAsync(ImageDataLibrary.Models.FullImage image)
    {
        return base.Channel.PostImageAsync(image);
    }
    
    public ImageDataLibrary.Models.FullImage PutImage(ImageDataLibrary.Models.FullImage image)
    {
        return base.Channel.PutImage(image);
    }
    
    public System.Threading.Tasks.Task<ImageDataLibrary.Models.FullImage> PutImageAsync(ImageDataLibrary.Models.FullImage image)
    {
        return base.Channel.PutImageAsync(image);
    }
    
    public bool DeleteImage(System.Guid id)
    {
        return base.Channel.DeleteImage(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteImageAsync(System.Guid id)
    {
        return base.Channel.DeleteImageAsync(id);
    }
}
